CREATE ROLE "qolboard_api" WITH LOGIN PASSWORD 'password';
GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA public TO qolboard_api;
GRANT USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO qolboard_api;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE, INSERT ON TABLES TO qolboard_api;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, UPDATE ON SEQUENCES TO qolboard_api;
