CREATE ROLE "qolboard_api" WITH LOGIN PASSWORD 'password';
GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA public TO qolboard_api;
GRANT USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO qolboard_api;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE, INSERT ON TABLES TO qolboard_api;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, UPDATE ON SEQUENCES TO qolboard_api;

CREATE ROLE "qolboard_migrations" WITH LOGIN PASSWORD 'password';
GRANT CREATE ON SCHEMA public TO qolboard_migrations;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public TO qolboard_migration;
GRANT USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO qolboard_migration;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO qolboard_migrate;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, UPDATE ON SEQUENCES TO qolboard_migrate;
